// Code generated by "stringer -type attr -trimprefix attr"; DO NOT EDIT.

package stun

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[attrMappedAddress-1]
	_ = x[attrUsername-6]
	_ = x[attrMessageIntegrity-8]
	_ = x[attrErrorCode-9]
	_ = x[attrUnknownAttributes-10]
	_ = x[attrChannelNumber-12]
	_ = x[attrLifeTime-13]
	_ = x[attrXorPeerAddress-18]
	_ = x[attrData-19]
	_ = x[attrRealm-20]
	_ = x[attrNonce-21]
	_ = x[attrXorRelayedAddress-22]
	_ = x[attrRequestedAddressFamily-23]
	_ = x[attrMessageIntegritySHA256-28]
	_ = x[attrUserHash-30]
	_ = x[attrXorMappedAddress-32]
	_ = x[attrReservationToken-34]
	_ = x[attrPriority-36]
	_ = x[attrUseCandidate-37]
	_ = x[attrPadding-38]
	_ = x[attrResponsePort-39]
	_ = x[attrConnectionID-42]
	_ = x[attrPasswordAlgorithms-32770]
	_ = x[attrSoftware-32802]
	_ = x[attrFingerprint-32808]
}

const _attr_name = "MappedAddressUsernameMessageIntegrityErrorCodeUnknownAttributesChannelNumberLifeTimeXorPeerAddressDataRealmNonceXorRelayedAddressRequestedAddressFamilyMessageIntegritySHA256UserHashXorMappedAddressReservationTokenPriorityUseCandidatePaddingResponsePortConnectionIDPasswordAlgorithmsSoftwareFingerprint"

var _attr_map = map[attr]string{
	1:     _attr_name[0:13],
	6:     _attr_name[13:21],
	8:     _attr_name[21:37],
	9:     _attr_name[37:46],
	10:    _attr_name[46:63],
	12:    _attr_name[63:76],
	13:    _attr_name[76:84],
	18:    _attr_name[84:98],
	19:    _attr_name[98:102],
	20:    _attr_name[102:107],
	21:    _attr_name[107:112],
	22:    _attr_name[112:129],
	23:    _attr_name[129:151],
	28:    _attr_name[151:173],
	30:    _attr_name[173:181],
	32:    _attr_name[181:197],
	34:    _attr_name[197:213],
	36:    _attr_name[213:221],
	37:    _attr_name[221:233],
	38:    _attr_name[233:240],
	39:    _attr_name[240:252],
	42:    _attr_name[252:264],
	32770: _attr_name[264:282],
	32802: _attr_name[282:290],
	32808: _attr_name[290:301],
}

func (i attr) String() string {
	if str, ok := _attr_map[i]; ok {
		return str
	}
	return "attr(" + strconv.FormatInt(int64(i), 10) + ")"
}
